openapi: 3.0.3
info:
  title: Free Shelf Storage Space Services - OpenAPI 3.0
  description: |-
    Free Shelf API Spec
  version: 0.0.1
  contact:
    name: API Support
    email: work.mitakshar@gmail.com
servers:
  - url: http://localhost:8080
tags:
  - name: Free Shelf api  v1
    description: Free Shelf - Online Free Storage Rental Service
paths:
  /v1/storagespace:
    post:
      tags:
        - storage space controller v1
      summary: Add New Storage Space
      description: Add New Storage Space
      operationId: createStorageSpace
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
      requestBody:
        description: Add New Storage Space
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/CreateStorageSpaceRequest'
        required: true
      responses:
        '201':
          description: "Add New Storage Space Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/StorageSpaceResponse'
        '422':
          description: "Add New Storage Space Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
    get:
      tags:
        - storage space controller v1
      summary: Get Storage Space
      description: Get Storage Space
      operationId: getStorageSpaces
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
      responses:
        '201':
          description: "Get Storage Spaces Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/StorageSpaceResponse'
        '422':
          description: "Get Storage Spaces Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
    put:
      tags:
        - storage space controller v1
      summary: Publish Storage Space
      description: Publish Storage Space
      operationId: publishStorageSpace
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
        - in: query
          name: "spaceId"
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '201':
          description: "Publish Storage Space Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '422':
          description: "Publish Storage Space Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'

  /v1/storagespace/addImages/{storageSpaceId}:
    post:
      tags:
        - storage space controller v1
      summary: Add New Storage Space Images
      description: Add New Storage Space Images
      operationId: addStorageSpaceImages
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
        - in: path
          name: storageSpaceId
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Image files to upload (up to 5 images)
                captions:
                  type: array
                  items:
                    type: string
                  description: Captions for each image in the same order (optional)
      responses:
        '201':
          description: "Add New Storage Space Image Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/SpaceImageResponse'
        '422':
          description: "Add New Storage Space Image Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'

  /v1/storagespace/{spaceId}/images/{imageId}:
    put:
      operationId: setImageAsPrimary
      summary: Set a specific image as the primary image
      tags:
        - storage space controller v1
      parameters:
        - name: spaceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: imageId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Image successfully set as primary
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/SpaceImageResponse'
        '404':
          description: Space or image not found

  /v1/storagespace/find:
    post:
      operationId: findNearestStorageSpace
      summary: Find Nearest Storage Space Available for User
      tags:
        - storage space controller v1
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/FindNearestStorageSpaceRequest'
      responses:
        '200':
          description: Storage Space successfully found
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/StorageSpaceResponse'
        '404':
          description: Space  not found

  /v1/storagespace/updateAvailability:
    post:
      operationId: updateAvailabilityPeriod
      summary: Update The Availability Period for the Storage Space
      tags:
        - storage space controller v1
      parameters:
        - in: header
          name: "Authorization"
          required: true
          schema:
            type: string
        - in: query
          name: "spaceId"
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/UpdateAvailabilityPeriodRequest'
      responses:
        '200':
          description: Storage Space Availability successfully Updated
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '404':
          description: Space  not found


