openapi: 3.0.3
info:
  title: Free Shelf User endpoints - OpenAPI 3.0
  description: |-
    Free Shelf API Spec
  version: 0.0.1
  contact:
    name: API Support
    email: work.mitakshar@gmail.com
servers:
  - url: http://localhost:8080
tags:
  - name: Free Shelf api  v1
    description: Free Shelf - Online Free Storage Rental Service
paths:
  /v1/auth/signup:
    post:
      tags:
        - auth controller v1
      summary: Sign-Up/Register
      description: Sign up/Register New User
      operationId: signUp
      requestBody:
        description: Sign Up Request
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/SignUpRequest'
        required: true
      responses:
        '201':
          description: "Sign Up Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/AuthResponse'
        '422':
          description: "Signup Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '400':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'

  /v1/auth/signin:
    post:
      tags:
        - auth controller v1
      summary: Sign-In
      description: Sign-In
      operationId: signIn
      requestBody:
        description: Sign In Request
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/SignInRequest'
        required: true
      responses:
        '200':
          description: "Sign In Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/AuthResponse'
        '422':
          description: "Signup Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'

  /v1/user:
    put:
      tags:
        - user controller v1
      summary:  Update Profile
      description: Update Profile
      operationId: updateUser
      parameters:
        - in: header
          name: "Authorization"
          schema:
            type: string
          required: true
      requestBody:
        description: Update Profile Request
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/UpdateProfileRequest'
        required: true
      responses:
        '200':
          description: "Update Profile Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '422':
          description: "Signup Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
    get:
      tags:
        - user controller v1
      summary: Get User Profile
      description: Get User Profile
      operationId: getUser
      parameters:
        - in: header
          name: "Authorization"
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Get Profile Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/UserProfileResponse'
        '422':
          description: "Get Profile Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'

  /v1/user/address:
    post:
      tags:
        - user controller v1
      summary: Add new Address for User
      description: Add new Address for User
      operationId: addAddress
      parameters:
        - in: header
          name: "Authorization"
          schema:
            type: string
          required: true
      requestBody:
        description: Add new Address Request
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/AddNewAddressRequest'
        required: true
      responses:
        '201':
          description: "Add new Address for User Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '422':
          description: "Add new Address  Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
    put:
      tags:
        - user controller v1
      summary: Edit Address for User
      description: Edit Address for User
      operationId: editAddress
      parameters:
        - in: header
          name: "Authorization"
          schema:
            type: string
          required: true
      requestBody:
        description: Edit Address Request
        content:
          application/json:
            schema:
              $ref: './FreeShelfApiComponents.yaml#/components/schemas/EditAddressRequest'
        required: true
      responses:
        '200':
          description: "Edit Address for User Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '422':
          description: "Edit Address  Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
    get:
      tags:
        - user controller v1
      summary: Get Addresses for User
      description: Get Addresses for User
      operationId: getAddresses
      parameters:
        - in: header
          name: "Authorization"
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Get Addresses for User Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/AddressResponse'
        '422':
          description: "Get Addresses  Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
    delete:
      tags:
        - user controller v1
      summary: Delete Address for User
      description: Delete Address for User
      operationId: deleteAddress
      parameters:
        - in: header
          name: "Authorization"
          schema:
            type: string
          required: true
        - in: query
          name: "addressId"
          schema:
            type: long
          required: true
      responses:
        '200':
          description: "Delete Address for User Success"
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '422':
          description: "Delete Address  Request is valid but the service was not able to process it ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'
        '401':
          description: "Validations failed for request arguments ..."
          content:
            application/json:
              schema:
                $ref: './FreeShelfApiComponents.yaml#/components/schemas/FreeShelfApiBaseApiResponse'


