package com.freeshelf.api.utils.enums;

public enum NotificationType {
  BOOKING_REQUEST, BOOKING_APPROVED, BOOKING_REJECTED, BOOKING_CANCELLED, NEW_MESSAGE, NEW_REVIEW, NEW_RATING, PAYMENT_RECEIVED, PAYMENT_FAILED, SYSTEM_ANNOUNCEMENT
}
