package com.freeshelf.api.utils.enums;

public enum SpaceFeature {
  CLIMATE_CONTROLLED, SECURITY_CAMERA, TWENTY_FOUR_HOUR_ACCESS, DRIVE_UP_ACCESS, INDOOR, OUTDOOR, LOCKED, SHELVING, ELECTRICITY, LIGHTING, ALARM_SYSTEM
}
